FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
RUN mkdir -p /app
WORKDIR /app
COPY knowledge_retriever/embedding/requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY . .
EXPOSE 8082
CMD ["uvicorn","knowledge_retriever.embedding.main:app", "--host", "0.0.0.0", "--port", "8082"]
