FROM python:3.10.6
WORKDIR /app  
COPY knowledge_retriever/frontapp/requirements.txt .
RUN pip install -r requirements.txt 
COPY . . 
EXPOSE 7000
CMD [ "python", "-m", "knowledge_retriever.frontapp.app" ]
