apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kr-certificate
  namespace: dev
spec:
  secretName: kr-certificate-secret
  dnsNames:
  - kr.inetumnlpcluster.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
