apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: embedding
  name: embedding
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: embedding
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: embedding
    spec:
      containers:
        - args:
            - uvicorn
            - knowledge_retriever.embedding.main:app
            - --host
            - 0.0.0.0
            - --port
            - "8082"
          env:
            - name: KR_embeddings__embedding_model
              value: '"text-embedding-ada-002"'
            - name: KR_embeddings__mode
              value: '"local"'
          image: $containerRegistryRemotePath/embedding:56f8667c00557e380fb24fe52b6dce9ed269d3f9
          name: embedding
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
