apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: knowledgeretriever
  name: knowledgeretriever
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: knowledgeretriever
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: knowledgeretriever
    spec:
      containers:
        - args:
            - uvicorn
            - knowledge_retriever.app:app
            - --host
            - 0.0.0.0
            - --port
            - "80"
          env:
            - name: KR_embeddings__embedding_model
              value: '"text-embedding-ada-002"'
            - name: KR_embeddings__mode
              value: '"remote"'
            - name: KR_embeddings__url
              value: '"http://embedding:8082"'
            - name: KR_vectorstore__mode
              value: '"local"'
          image: $containerRegistryRemotePath/knowledgeretriever:2e9829ee672a5955f10d187718af7b9ab994c707
          name: knowledgeretriever
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /app/chroma_persist
              name: knowledgeretriever-claim0
      restartPolicy: Always
      volumes:
        - name: knowledgeretriever-claim0
          persistentVolumeClaim:
            claimName: knowledgeretriever-claim0
status: {}
