apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: knowledgeretriever-claim0
  name: knowledgeretriever-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
  volumeName: pv-kr-dev
  storageClassName: managed-csi
status: {}
